[versions]
automatone = "0.11.0"
blabber = "1.5.1-mc1.20.1"
cca = "5.2.2"
chenille = "0.12.0"
chime = "cec3bcbaed508eb5f564deac8c33923dcccfdf7e"
cloth = "11.1.118"
fiberToCloth = "v3-SNAPSHOT"
fiber = "0.23.0-2"
fpa = "0.2-SNAPSHOT"
impersonate = "2.10.2"
locki = "0.11.0"
loom = "1.6.+"
modmenu = "7.2.2"
pal = "1.8.0"
rea = "2.4.0"
satin = "1.14.0"

[libraries]
automatone = { group = "io.github.ladysnake", name = "automatone", version.ref = "automatone" }
blabber = { group = "org.ladysnake", name = "blabber", version.ref = "blabber" }
cca-base = { group = "dev.onyxstudios.cardinal-components-api", name="cardinal-components-base", version.ref = "cca" }
cca-entity = { group = "dev.onyxstudios.cardinal-components-api", name="cardinal-components-entity", version.ref = "cca" }
cca-scoreboard = { group = "dev.onyxstudios.cardinal-components-api", name="cardinal-components-scoreboard", version.ref = "cca" }
cca-world = { group = "dev.onyxstudios.cardinal-components-api", name="cardinal-components-world", version.ref = "cca" }
chime = { group = "com.github.emilyploszaj", name = "chime", version.ref = "chime" }
clothConfig = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth" }
fabricPermissionsApi = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fpa" }
fiber = { group = "me.zeroeightsix", name = "fiber", version.ref = "fiber" }
fiberToCloth = { group = "com.github.pyrofab", name = "fibertocloth", version.ref = "fiberToCloth" }
impersonate = { group = "org.ladysnake", name = "impersonate", version.ref = "impersonate" }
locki = { group = "org.ladysnake", name = "locki", version.ref = "locki" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
playerAbilityLib = { group = "io.github.ladysnake", name = "PlayerAbilityLib", version.ref = "pal" }
reachEntityAttributes = { group = "com.jamieswhiteshirt", name = "reach-entity-attributes", version.ref = "rea" }
satin = { group = "org.ladysnake", name = "satin", version.ref = "satin" }

[bundles]
requiredLibraries = [
    "automatone",
    "blabber",
    "chime",
    "cca-base",
    "cca-entity",
    "cca-scoreboard",
    "cca-world",
    "fabricPermissionsApi",
    "fiber",
    "impersonate",
    "locki",
    "playerAbilityLib",
    "reachEntityAttributes",
    "satin",
]
cloth = ["clothConfig", "fiberToCloth"]

[plugins]
chenille = { id = "io.github.ladysnake.chenille", version.ref = "chenille" }
quilt-loom = { id = "org.quiltmc.loom", version.ref = "loom" }
